### ISSUE TITLE
UPDATE_FIRMWARE is failing

### ISSUE THREAD

**Issue by idarlund** [hak5/sharkjack-payloads#53]
Hi,

Not sure where to post this issue. Let me know if I should post it somewhere else.

When initiating UPDATE_FIRMWARE on the new shark jack cable it's failing with:
`root@shark:/# UPDATE_FIRMWARE 
Checking internet connection
Checking for updates
cat: can't open '/tmp/firmware_check': No such file or directory
`

After some debugging it seems it does not trust the https certificate:
`root@shark:/# wget https://downloads.hak5.org/api/devices/sharkjack-cable/firmwa
res -O /tmp/firmware_check
Downloading 'https://downloads.hak5.org/api/devices/sharkjack-cable/firmwares'
Connecting to 142.250.74.179:443
Connection error: Invalid SSL certificate`

**Comment by idarlund** [comment]
This also affects opkg:
Collected errors:
 * opkg_download: Failed to download http://downloads.hak5.org/packages/shark/1907//Packages.gz, wget returned 5.

**Comment by hak5darren** [comment]
Verify with the date command, and if necessary rectify this with an NTP update manually using the command ntpd -q -p 1.openwrt.pool.ntp.org

**Comment by idarlund** [comment]
That worked perfectly! A bit embarrassed that I didn't check the date 😅
Anyway, case closed! ❤️
